version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - cd ..
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - **/*
  discard-paths: yes