version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    command:
      - mvn clean package:
  
  post_build:
    command:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes